# Generated by Django 5.1.4 on 2025-02-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('angajare', '0001_initial'),
        ('recrutare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='angajat',
            name='pozitie_angajat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutare.pozitie'),
        ),
        migrations.AddField(
            model_name='angajat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='angajat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angajare.angajat'),
        ),
        migrations.AddField(
            model_name='document',
            name='angajat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angajare.angajat'),
        ),
        migrations.AddField(
            model_name='statisticaadaugaredocumente',
            name='angajat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angajare.angajat'),
        ),
        migrations.AddField(
            model_name='statisticaadaugaredocumente',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angajare.document'),
        ),
        migrations.AddField(
            model_name='statisticaadaugaredocumente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statisticaangajare',
            name='angajat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angajare.angajat'),
        ),
        migrations.AddField(
            model_name='statisticaangajare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
