# Generated by Django 5.1.4 on 2025-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angajare', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='mod_de_lucru',
            field=models.CharField(choices=[('birou', 'Birou'), ('hibrid', 'Hibrid'), ('remote', 'Remote')], default='birou', help_text='Selectati modul de lucru', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tip_contract',
            field=models.CharField(choices=[('determinat', 'Determinat'), ('nedeterminat', 'Nedeterminat')], default='nedeterminat', help_text='Selectati tipul contractului', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='tip_document',
            field=models.CharField(help_text='Introduceti tipul documentului (ex: CI, contract, diploma etc.)', max_length=100),
        ),
    ]
